"""Data loading utilities for pre-generated sequence datasets.

These helpers make it easy to feed deterministic target sequences to the
sequence guessing environment or perform offline analysis. They are designed
around the JSONL outputs produced by :mod:`src.data.sequence_bank`.
"""

from __future__ import annotations

import copy
import json
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, Iterator, List, Optional, Sequence, Tuple, Union

from hydra.utils import to_absolute_path
from omegaconf import DictConfig, OmegaConf


@dataclass(frozen=True)
class SequenceRecord:
    """Single sequence entry loaded from a sequence bank dataset."""

    id: str
    sequence: List[int]
    family: str
    sequence_length: int
    index: int
    seed: int
    metadata: Dict[str, Any]

    def to_metadata(self) -> Dict[str, Any]:
        """Return a copy of descriptive metadata for downstream logging."""
        payload: Dict[str, Any] = {
            "id": self.id,
            "family": self.family,
            "sequence_length": self.sequence_length,
            "index": self.index,
            "seed": self.seed,
        }
        if self.metadata:
            # Avoid mutating internal metadata structures.
            payload.update(copy.deepcopy(self.metadata))
        return payload


class SequenceBankDataset(Sequence[SequenceRecord]):
    """In-memory dataset backed by a JSONL sequence bank export."""

    def __init__(
        self,
        path: Union[str, Path],
        *,
        sequence_length: Optional[int] = None,
        families: Optional[Iterable[str]] = None,
        limit: Optional[int] = None,
        strict: bool = True,
    ) -> None:
        """Load dataset entries from ``path``.

        Args:
            path: Path to the JSONL file generated by the sequence bank.
            sequence_length: If provided, only sequences with this length are kept.
            families: Optional iterable of family names to keep.
            limit: Optional maximum number of records to load.
            strict: When ``True`` and the filters discard every record, raises an
                error; when ``False`` an empty dataset is allowed.
        """
        abs_path = Path(to_absolute_path(str(path)))
        if not abs_path.is_file():
            raise FileNotFoundError(f"Sequence dataset not found at {abs_path}")

        family_filter = set(families) if families else None
        self._records: List[SequenceRecord] = []

        with abs_path.open("r", encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                payload = json.loads(line)

                raw_sequence = payload.get("sequence", [])
                sequence = [int(value) for value in raw_sequence]
                record = SequenceRecord(
                    id=str(payload.get("id", f"record_{len(self._records)}")),
                    sequence=sequence,
                    family=str(payload.get("family", "unknown")),
                    sequence_length=int(payload.get("sequence_length", len(sequence))),
                    index=int(payload.get("index", len(self._records))),
                    seed=int(payload.get("seed", -1)),
                    metadata=payload.get("metadata", {}) or {},
                )

                if sequence_length is not None and record.sequence_length != sequence_length:
                    continue
                if family_filter and record.family not in family_filter:
                    continue

                self._records.append(record)

                if limit is not None and len(self._records) >= int(limit):
                    break

        if strict and not self._records:
            filters = []
            if sequence_length is not None:
                filters.append(f"sequence_length={sequence_length}")
            if family_filter:
                filters.append(f"families={sorted(family_filter)}")
            filter_desc = ", ".join(filters) if filters else "no filters"
            raise ValueError(
                f"No records loaded from {abs_path} (applied {filter_desc})."
            )

        self.path = abs_path
        self._family_filter = family_filter
        self._sequence_length = sequence_length

    def __len__(self) -> int:  # pragma: no cover - trivial
        return len(self._records)

    def __getitem__(self, index: int) -> SequenceRecord:  # pragma: no cover - trivial
        return self._records[index]

    def __iter__(self) -> Iterator[SequenceRecord]:  # pragma: no cover - trivial
        return iter(self._records)

    @property
    def sequence_length(self) -> Optional[int]:
        """Return the enforced sequence length if one was configured."""
        return self._sequence_length

    @property
    def families(self) -> List[str]:
        """List of family names present in the dataset."""
        return sorted({record.family for record in self._records})

    def summary(self) -> Dict[str, Any]:
        """Return lightweight summary statistics."""
        return {
            "size": len(self._records),
            "path": str(self.path),
            "sequence_length": self._sequence_length,
            "families": self.families,
        }


class SequenceBankDataLoader:
    """Deterministic iterator over :class:`SequenceBankDataset` entries."""

    def __init__(
        self,
        dataset: SequenceBankDataset,
        *,
        shuffle: bool = True,
        cycle: bool = True,
        seed: Optional[int] = None,
    ) -> None:
        if len(dataset) == 0:
            raise ValueError("Cannot create data loader from empty dataset")

        self.dataset = dataset
        self.shuffle = shuffle
        self.cycle = cycle
        self._rng = random.Random(seed)

        self._order: List[int] = []
        self._cursor = 0
        self.reset()

    def __len__(self) -> int:  # pragma: no cover - trivial
        return len(self.dataset)

    def reset(self) -> None:
        """Reset iteration order (shuffling if enabled)."""
        self._order = list(range(len(self.dataset)))
        if self.shuffle:
            self._rng.shuffle(self._order)
        self._cursor = 0

    def _next_record(self) -> SequenceRecord:
        if self._cursor >= len(self._order):
            if not self.cycle:
                raise StopIteration("Sequence dataset exhausted")
            self.reset()
        record = self.dataset[self._order[self._cursor]]
        self._cursor += 1
        return record

    def next_sequence(self, expected_length: Optional[int] = None) -> Tuple[List[int], Dict[str, Any]]:
        """Return the next sequence and associated metadata.

        Args:
            expected_length: Optional length guard. When provided the loader
                verifies that the sampled record matches the expectation.

        Returns:
            A tuple ``(sequence, metadata)`` where ``sequence`` is a list of
            integers and ``metadata`` contains descriptive fields.
        """
        record = self._next_record()

        if expected_length is not None and record.sequence_length != expected_length:
            raise ValueError(
                "Sequence length mismatch: expected "
                f"{expected_length}, found {record.sequence_length}"
            )

        return list(record.sequence), record.to_metadata()


def _to_config_dict(cfg: Union[DictConfig, Dict[str, Any], None]) -> Dict[str, Any]:
    if cfg is None:
        return {}
    if isinstance(cfg, DictConfig):
        return dict(OmegaConf.to_container(cfg, resolve=True))
    return dict(cfg)


def create_sequence_loader(
    cfg: Union[DictConfig, Dict[str, Any], None],
    *,
    sequence_length: int,
) -> SequenceBankDataLoader:
    """Factory for :class:`SequenceBankDataLoader` from Hydra-friendly config."""
    cfg_dict = _to_config_dict(cfg)
    path = cfg_dict.get("path")
    if not path:
        raise ValueError("`data_loader.path` must be provided when enabling dataset loading")

    families = cfg_dict.get("families")
    limit = cfg_dict.get("limit")
    strict = cfg_dict.get("strict", True)

    dataset = SequenceBankDataset(
        path=path,
        sequence_length=sequence_length,
        families=families,
        limit=limit,
        strict=strict,
    )

    loader = SequenceBankDataLoader(
        dataset,
        shuffle=cfg_dict.get("shuffle", True),
        cycle=cfg_dict.get("cycle", True),
        seed=cfg_dict.get("seed"),
    )
    return loader


__all__ = [
    "SequenceRecord",
    "SequenceBankDataset",
    "SequenceBankDataLoader",
    "create_sequence_loader",
]
